name = "cmtz"
type = "webpack"
account_id = "63646b37a40a3fdce7d248c2648d0941"
workers_dev = true
route = "*certifiedmixtapes.com/*"
zone_id = ""


[site]
bucket = "./dist/browser"
entry-point = "workers-site"
